#pragma once

//--------------------------------------------------------------------------------------
// This file is automatically generated by the compiler for use outside of the math
// engine. This file must end with an empty line!
//--------------------------------------------------------------------------------------

